
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_ACCEL_MB_AXI_GPIO_TSC_DEVICE_ID,
		XPAR_ACCEL_MB_AXI_GPIO_TSC_BASEADDR,
		XPAR_ACCEL_MB_AXI_GPIO_TSC_INTERRUPT_PRESENT,
		XPAR_ACCEL_MB_AXI_GPIO_TSC_IS_DUAL
	}
};


