
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmbox.h"

/*
 * The configuration table for devices
 */

XMbox_Config XMbox_ConfigTable[] =
{
	{
		 XPAR_ACCEL_SHARED_MAILBOX_IF_1_DEVICE_ID, 
		 XPAR_ACCEL_SHARED_MAILBOX_IF_1_BASEADDR, 
		 XPAR_ACCEL_SHARED_MAILBOX_IF_1_USE_FSL,
		 XPAR_ACCEL_SHARED_MAILBOX_IF_1_SEND_FSL,
		 XPAR_ACCEL_SHARED_MAILBOX_IF_1_RECV_FSL
	},
};
