
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtmrctr.h"

/*
* The configuration table for devices
*/

XTmrCtr_Config XTmrCtr_ConfigTable[XPAR_XTMRCTR_NUM_INSTANCES] =
{
	{
		XPAR_ACCEL_MB_AXI_TIMER_DEVICE_ID,
		XPAR_ACCEL_MB_AXI_TIMER_BASEADDR,
		XPAR_ACCEL_MB_AXI_TIMER_CLOCK_FREQ_HZ
	}
};


